Category.delete_all

Category.create(name:'Портрет', id:1)
Category.create(name:'Природа', id:2)
Category.create(name:'Місто', id:3)



Pic.delete_all

Pic.create(title:'1', description:'...', :image => File.open("public/images/42.jpg"), category_id:1)
Pic.create(title:'2', description:'...', :image => File.open("public/images/43.jpg"), category_id:1)
Pic.create(title:'3', description:'...', :image => File.open("public/images/44.jpg"), category_id:1)
Pic.create(title:'4', description:'...', :image => File.open("public/images/45.jpg"), category_id:1)
Pic.create(title:'5', description:'...', :image => File.open("public/images/46.jpg"), category_id:1)
Pic.create(title:'6', description:'...', :image => File.open("public/images/47.jpg"), category_id:1)
Pic.create(title:'7', description:'...', :image => File.open("public/images/48.jpg"), category_id:1)
Pic.create(title:'8', description:'...', :image => File.open("public/images/49.jpg"), category_id:1)
Pic.create(title:'9', description:'...', :image => File.open("public/images/50.jpg"), category_id:1)
Pic.create(title:'10', description:'...', :image => File.open("public/images/51.jpg"), category_id:1)
Pic.create(title:'12', description:'...', :image => File.open("public/images/53.jpg"), category_id:1)
Pic.create(title:'13', description:'...', :image => File.open("public/images/54.jpg"), category_id:1)
Pic.create(title:'14', description:'...', :image => File.open("public/images/55.jpg"), category_id:1)
Pic.create(title:'15', description:'...', :image => File.open("public/images/56.jpg"), category_id:1)
Pic.create(title:'16', description:'...', :image => File.open("public/images/57.jpg"), category_id:1)
Pic.create(title:'17', description:'...', :image => File.open("public/images/58.jpg"), category_id:1)
Pic.create(title:'18', description:'...', :image => File.open("public/images/59.jpg"), category_id:1)
Pic.create(title:'19', description:'...', :image => File.open("public/images/60.jpg"), category_id:1)
Pic.create(title:'20', description:'...', :image => File.open("public/images/61.jpg"), category_id:1)
Pic.create(title:'21', description:'...', :image => File.open("public/images/62.jpg"), category_id:1)
Pic.create(title:'22', description:'...', :image => File.open("public/images/63.jpg"), category_id:1)
Pic.create(title:'23', description:'...', :image => File.open("public/images/64.jpg"), category_id:1)
Pic.create(title:'24', description:'...', :image => File.open("public/images/65.jpg"), category_id:1)
Pic.create(title:'25', description:'...', :image => File.open("public/images/66.jpg"), category_id:1)
Pic.create(title:'26', description:'...', :image => File.open("public/images/67.jpg"), category_id:1)
Pic.create(title:'27', description:'...', :image => File.open("public/images/68.jpg"), category_id:1)
Pic.create(title:'28', description:'...', :image => File.open("public/images/69.jpg"), category_id:1)
Pic.create(title:'29', description:'...', :image => File.open("public/images/70.jpg"), category_id:1)
Pic.create(title:'30', description:'...', :image => File.open("public/images/71.jpg"), category_id:1)
Pic.create(title:'31', description:'...', :image => File.open("public/images/72.jpg"), category_id:1)
Pic.create(title:'32', description:'...', :image => File.open("public/images/73.jpg"), category_id:1)
Pic.create(title:'33', description:'...', :image => File.open("public/images/74.jpg"), category_id:1)


Pic.create(title:'34', description:'...', :image => File.open("public/images/75.jpg"), category_id:2)
Pic.create(title:'35', description:'...', :image => File.open("public/images/76.jpg"), category_id:2)
Pic.create(title:'36', description:'...', :image => File.open("public/images/77.jpg"), category_id:2)
Pic.create(title:'37', description:'...', :image => File.open("public/images/78.jpg"), category_id:2)
Pic.create(title:'38', description:'...', :image => File.open("public/images/79.jpg"), category_id:2)
Pic.create(title:'39', description:'...', :image => File.open("public/images/80.jpg"), category_id:2)
Pic.create(title:'40', description:'...', :image => File.open("public/images/81.jpg"), category_id:2)
Pic.create(title:'41', description:'...', :image => File.open("public/images/82.jpg"), category_id:2)
Pic.create(title:'42', description:'...', :image => File.open("public/images/83.jpg"), category_id:2)
Pic.create(title:'43', description:'...', :image => File.open("public/images/84.jpg"), category_id:2)
Pic.create(title:'44', description:'...', :image => File.open("public/images/85.jpg"), category_id:2)
Pic.create(title:'45', description:'...', :image => File.open("public/images/86.jpg"), category_id:2)
Pic.create(title:'46', description:'...', :image => File.open("public/images/87.jpg"), category_id:2)
Pic.create(title:'47', description:'...', :image => File.open("public/images/88.jpg"), category_id:2)

Pic.create(title:'49', description:'...', :image => File.open("public/images/1.jpg"), category_id:3)
Pic.create(title:'50', description:'...', :image => File.open("public/images/2.jpg"), category_id:3)
Pic.create(title:'51', description:'...', :image => File.open("public/images/3.jpg"), category_id:3)
Pic.create(title:'52', description:'...', :image => File.open("public/images/4.jpg"), category_id:3)
Pic.create(title:'53', description:'...', :image => File.open("public/images/5.jpg"), category_id:3)
Pic.create(title:'54', description:'...', :image => File.open("public/images/6.jpg"), category_id:3)
Pic.create(title:'55', description:'...', :image => File.open("public/images/7.jpg"), category_id:3)
Pic.create(title:'56', description:'...', :image => File.open("public/images/8.jpg"), category_id:3)
Pic.create(title:'57', description:'...', :image => File.open("public/images/9.jpg"), category_id:3)
Pic.create(title:'58', description:'...', :image => File.open("public/images/10.jpg"), category_id:3)
Pic.create(title:'59', description:'...', :image => File.open("public/images/11.jpg"), category_id:3)
Pic.create(title:'60', description:'...', :image => File.open("public/images/12.jpg"), category_id:3)
Pic.create(title:'61', description:'...', :image => File.open("public/images/13.jpg"), category_id:3)
Pic.create(title:'62', description:'...', :image => File.open("public/images/14.jpg"), category_id:3)
Pic.create(title:'63', description:'...', :image => File.open("public/images/15.jpg"), category_id:3)
Pic.create(title:'64', description:'...', :image => File.open("public/images/16.jpg"), category_id:3)
Pic.create(title:'65', description:'...', :image => File.open("public/images/17.jpg"), category_id:3)
Pic.create(title:'66', description:'...', :image => File.open("public/images/18.jpg"), category_id:3)
Pic.create(title:'67', description:'...', :image => File.open("public/images/19.jpg"), category_id:3)
Pic.create(title:'68', description:'...', :image => File.open("public/images/20.jpg"), category_id:3)
Pic.create(title:'69', description:'...', :image => File.open("public/images/21.jpg"), category_id:3)
Pic.create(title:'70', description:'...', :image => File.open("public/images/22.jpg"), category_id:3)
Pic.create(title:'71', description:'...', :image => File.open("public/images/23.jpg"), category_id:3)
Pic.create(title:'72', description:'...', :image => File.open("public/images/24.jpg"), category_id:3)
Pic.create(title:'73', description:'...', :image => File.open("public/images/25.jpg"), category_id:3)
Pic.create(title:'74', description:'...', :image => File.open("public/images/26.jpg"), category_id:3)
Pic.create(title:'75', description:'...', :image => File.open("public/images/27.jpg"), category_id:3)
Pic.create(title:'76', description:'...', :image => File.open("public/images/28.jpg"), category_id:3)
Pic.create(title:'77', description:'...', :image => File.open("public/images/29.jpg"), category_id:3)
Pic.create(title:'78', description:'...', :image => File.open("public/images/30.jpg"), category_id:3)
Pic.create(title:'79', description:'...', :image => File.open("public/images/31.jpg"), category_id:3)
Pic.create(title:'80', description:'...', :image => File.open("public/images/32.jpg"), category_id:3)
Pic.create(title:'81', description:'...', :image => File.open("public/images/33.jpg"), category_id:3)
Pic.create(title:'82', description:'...', :image => File.open("public/images/34.jpg"), category_id:3)
Pic.create(title:'83', description:'...', :image => File.open("public/images/35.jpg"), category_id:3)
Pic.create(title:'84', description:'...', :image => File.open("public/images/36.jpg"), category_id:3)
Pic.create(title:'85', description:'...', :image => File.open("public/images/37.jpg"), category_id:3)
Pic.create(title:'86', description:'...', :image => File.open("public/images/38.jpg"), category_id:3)
Pic.create(title:'87', description:'...', :image => File.open("public/images/39.jpg"), category_id:3)
Pic.create(title:'88', description:'...', :image => File.open("public/images/40.jpg"), category_id:3)
Pic.create(title:'89', description:'...', :image => File.open("public/images/41.jpg"), category_id:3)